metricbeat.modules:
- module: system
  metricsets: ["cpu","memory","network","uptime"]
  enabled: true
  period: 15s
  processes: ['.*']
  ### Custom edit ###
  cpu.metrics:  ["percentages"]
  core.metrics: ["percentages"]
  ### End of custom edit ###

  #- module: apache
  # metricsets: ["status"]
  #enabled: true
  #period: 5s
  #hosts: ["http://172.20.11.7"]
- module: docker
  metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"]
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
        #output.logstash:
        #  hosts: ["logstash:5044"]
  #  loadbalance: true
  #ssl.enabled: true

  #setup.dashboards.enabled: true
setup.kibana:
  host: "kibana:5601"
setup.dashboards.enabled: true
  #setup.dashboards.always_kibana: true
setup.dashboards.retry_enabled: true
